apiVersion: 1
datasources:
  - name: Postgres-AF
    type: postgres
    access: proxy
    isDefault: true
    editable: true
    url: postgres:5432
    database: ${PG_DB}
    user: ${PG_USER}
    secureJsonData:
      password: ${PG_PASSWORD}
    jsonData:
      sslmode: "disable"
      postgresVersion: 1600
      timescaledb: false
