apiVersion: 1
datasources:
  - name: Postgres-AF
    type: postgres
    access: proxy
    isDefault: true
    editable: true
    url: postgres:5432
    database: af
    user: afuser
    secureJsonData:
      password: afpass
    jsonData:
      sslmode: "disable"
      postgresVersion: 1600
      timescaledb: false
